Message.create(greeting: 'Hello, world!')
Message.create(greeting: 'Hey, Heya or Hey there!')
Message.create(greeting: 'Its good to see you')
Message.create(greeting: 'Howdy!')
Message.create(greeting: 'Hi, there!')